/**
 * Regenerates supabase/seed.sql from the fixtures. The SQL is idempotent
 * (upserts keyed on code+term, wispr_meeting_id and slug), so it is safe to
 * re-run. Apply it with the Supabase MCP, the SQL editor, or `psql -f`.
 *
 * Usage: npm run seed:build
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { courses } from "../lib/fixtures/courses";

const root = join(__dirname, "..");
const read = (p: string) => readFileSync(join(root, p), "utf8");

const str = (v: string | null) => (v === null ? "null" : `'${v.replace(/'/g, "''")}'`);
const arr = (v: string[]) => `array[${v.map(str).join(", ")}]::text[]`;
/** Dollar-quote with a tag that cannot appear in the body. */
function dq(body: string) {
  let n = 0;
  while (body.includes(`$q${n}$`)) n++;
  return `$q${n}$${body}$q${n}$`;
}

const lectures = [
  {
    wispr: "2b8f0773-fb67-4389-9551-ff835a6b9f8a",
    course: "ECON 106F",
    startsAt: "2026-10-05T15:00:20Z",
    share: "https://notes.wisprflow.ai/shared/SGM_CQ-BnLpOzHMgAz0Apu9oKuvzE0FBAf7ObPjFKIU",
    transcript: read("lib/fixtures/transcripts/econ106f-class3.txt"),
    slug: "econ106f-class3",
    summary: "Value vs price, the NPV decision rule, and the first look at time value of money.",
    created: "2026-10-05T16:20:00Z",
  },
  {
    wispr: "9d6e4625-fd96-4a72-88a4-ddfb72888a8c",
    course: "COMM 187",
    startsAt: "2026-10-05T16:30:47Z",
    share: "https://notes.wisprflow.ai/shared/hB4i6GY_ZHhvg8Uin8e82Uv2ak0P4VSUA6LPGPn0lKA",
    transcript: null as string | null,
    slug: "comm187-class3",
    summary: "Fairness, personal vs professional ethics, objectivity, and conflicts of interest.",
    created: "2026-10-05T18:00:00Z",
  },
];

const out: string[] = ["-- GENERATED by scripts/build-seed.ts. Do not edit by hand.", "begin;"];

for (const c of courses) {
  out.push(
    `insert into public.courses (code, slug, title, category, instructor, schedule, color, tone, calendar_event_series_ids, aliases, term, generation_notes) values (${[
      str(c.code), str(c.slug), str(c.title), str(c.category), str(c.instructor), str(c.schedule), str(c.color), str(c.tone),
      arr(c.calendar_event_series_ids), arr(c.aliases), str(c.term), str(c.generation_notes),
    ].join(", ")})
on conflict (code, term) do update set slug = excluded.slug, title = excluded.title, category = excluded.category,
  instructor = excluded.instructor, schedule = excluded.schedule, color = excluded.color, tone = excluded.tone,
  calendar_event_series_ids = excluded.calendar_event_series_idss, aliases = excluded.aliases,
  generation_notes = excluded.generation_notes;`,
  );
}

for (const l of lectures) {
  out.push(
    `insert into public.lectures (course_id, wispr_meeting_id, starts_at, wispr_share_link, transcript, status)
values ((select id from public.courses where code = ${str(l.course)} and term = 'Fall 2026'), ${str(l.wispr)}, ${str(l.startsAt)}, ${str(l.share)}, ${l.transcript === null ? "null" : dq(l.transcript)}, 'generated')
on conflict (wispr_meeting_id) do update set course_id = excluded.course_id, starts_at = excluded.starts_at,
  wispr_share_link = excluded.wispr_share_link, transcript = excluded.transcript, status = excluded.status;`,
  );
  const specText = read(`lib/fixtures/lessons/${l.slug}.json`);
  const spec = JSON.parse(specText);
  out.push(
    `insert into public.lessons (slug, lecture_id, title, summary, est_minutes, spec, schema_version, created_at)
values (${str(l.slug)}, (select id from public.lectures where wispr_meeting_id = ${str(l.wispr)}), ${str(spec.title)}, ${str(l.summary)}, ${spec.est_minutes}, ${dq(JSON.stringify(spec))}::jsonb, ${spec.schema_version}, ${str(l.created)})
on conflict (slug) do update set lecture_id = excluded.lecture_id, title = excluded.title, summary = excluded.summary,
  est_minutes = excluded.est_minutes, spec = excluded.spec, schema_version = excluded.schema_version;`,
  );
}

out.push("commit;", "");
writeFileSync(join(root, "supabase", "seed.sql"), out.join("\n"));
console.log(`wrote supabase/seed.sql (${out.join("\n").length} bytes)`);
