// Generated by the Supabase MCP generate_typescript_types for project etvmpkygvfxwocvlrpya
// (helper generics Tables/TablesInsert/etc. omitted, the app does not use them).
// Regenerate after any schema change.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.18"
  }
  public: {
    Tables: {
      assessments: {
        Row: {
          canvas_url: string | null
          confidence: string | null
          course_id: string
          coverage: string | null
          created_at: string
          due_at: string | null
          format: string | null
          id: string
          kind: string
          source: string | null
          title: string
          weight: number | null
        }
        Insert: {
          canvas_url?: string | null
          confidence?: string | null
          course_id: string
          coverage?: string | null
          created_at?: string
          due_at?: string | null
          format?: string | null
          id?: string
          kind: string
          source?: string | null
          title: string
          weight?: number | null
        }
        Update: {
          canvas_url?: string | null
          confidence?: string | null
          course_id?: string
          coverage?: string | null
          created_at?: string
          due_at?: string | null
          format?: string | null
          id?: string
          kind?: string
          source?: string | null
          title?: string
          weight?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "assessments_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
        ]
      }
      attempts: {
        Row: {
          answer: Json | null
          block_id: string
          correct: boolean
          created_at: string
          id: string
          lesson_id: string
        }
        Insert: {
          answer?: Json | null
          block_id: string
          correct: boolean
          created_at?: string
          id?: string
          lesson_id: string
        }
        Update: {
          answer?: Json | null
          block_id?: string
          correct?: boolean
          created_at?: string
          id?: string
          lesson_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "attempts_lesson_id_fkey"
            columns: ["lesson_id"]
            isOneToOne: false
            referencedRelation: "lessons"
            referencedColumns: ["id"]
          },
        ]
      }
      concepts: {
        Row: {
          course_id: string
          created_at: string
          first_lesson_id: string | null
          id: string
          name: string
        }
        Insert: {
          course_id: string
          created_at?: string
          first_lesson_id?: string | null
          id?: string
          name: string
        }
        Update: {
          course_id?: string
          created_at?: string
          first_lesson_id?: string | null
          id?: string
          name?: string
        }
        Relationships: [
          {
            foreignKeyName: "concepts_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "concepts_first_lesson_id_fkey"
            columns: ["first_lesson_id"]
            isOneToOne: false
            referencedRelation: "lessons"
            referencedColumns: ["id"]
          },
        ]
      }
      courses: {
        Row: {
          aliases: string[]
          calendar_event_series_ids: string[]
          category: string
          code: string
          color: string
          created_at: string
          generation_notes: string | null
          id: string
          instructor: string | null
          schedule: string
          slug: string
          term: string
          title: string
          tone: string
        }
        Insert: {
          aliases?: string[]
          calendar_event_series_ids?: string[]
          category: string
          code: string
          color: string
          created_at?: string
          generation_notes?: string | null
          id?: string
          instructor?: string | null
          schedule: string
          slug: string
          term: string
          title: string
          tone?: string
        }
        Update: {
          aliases?: string[]
          calendar_event_series_ids?: string[]
          category?: string
          code?: string
          color?: string
          created_at?: string
          generation_notes?: string | null
          id?: string
          instructor?: string | null
          schedule?: string
          slug?: string
          term?: string
          title?: string
          tone?: string
        }
        Relationships: []
      }
      lectures: {
        Row: {
          calendar_event_id: string | null
          course_id: string | null
          created_at: string
          ends_at: string | null
          id: string
          starts_at: string | null
          status: string
          transcript: string | null
          wispr_meeting_id: string
          wispr_share_link: string | null
        }
        Insert: {
          calendar_event_id?: string | null
          course_id?: string | null
          created_at?: string
          ends_at?: string | null
          id?: string
          starts_at?: string | null
          status?: string
          transcript?: string | null
          wispr_meeting_id: string
          wispr_share_link?: string | null
        }
        Update: {
          calendar_event_id?: string | null
          course_id?: string | null
          created_at?: string
          ends_at?: string | null
          id?: string
          starts_at?: string | null
          status?: string
          transcript?: string | null
          wispr_meeting_id?: string
          wispr_share_link?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "lectures_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
        ]
      }
      lessons: {
        Row: {
          created_at: string
          est_minutes: number | null
          id: string
          lecture_id: string
          materials_missing: string | null
          schema_version: number
          slug: string
          spec: Json
          status: string
          summary: string | null
          title: string
        }
        Insert: {
          created_at?: string
          est_minutes?: number | null
          id?: string
          lecture_id: string
          materials_missing?: string | null
          schema_version?: number
          slug: string
          spec: Json
          status?: string
          summary?: string | null
          title: string
        }
        Update: {
          created_at?: string
          est_minutes?: number | null
          id?: string
          lecture_id?: string
          materials_missing?: string | null
          schema_version?: number
          slug?: string
          spec?: Json
          status?: string
          summary?: string | null
          title?: string
        }
        Relationships: [
          {
            foreignKeyName: "lessons_lecture_id_fkey"
            columns: ["lecture_id"]
            isOneToOne: false
            referencedRelation: "lectures"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

export const Constants = {
  public: {
    Enums: {},
  },
} as const
